services:

## Uptime Kuma 
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: kuma
    volumes:
      - ~/docker/ukuma/data:/app/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptimekuma.example.com`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=https"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    networks:
      - proxy

networks:
  proxy:
    external: true