api:
  dashboard: true
  debug: true
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics
#    addInternals: true
entryPoints:
  metrics:
    address: ":8082"
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true #  this is used for when using self signed certs behind traefik. i.e using traefik as the proxy
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  cloudflare:
    acme:
      email: ###
      storage: acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Staging
      caServer: https://acme-v02.api.letsencrypt.org/directory # Production
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare     
        #delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready        
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"